CREATE TABLE IF NOT EXISTS users {
    id INTEGER NOT NULL PRIMARY KEY,
    anilist_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
